- name: Install Nginx
  hosts: WEB
  become: true
  tasks:
    - name: Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Restart Nginx Service
      ansible.builtin.systemd:
        - name: nginx
          state: restarted
          enabled: yes