- name: Install Nginx
  hosts: WEB
  become: true
  tasks:
    - name: Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Start Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started

- name: Install Nginx
  hosts: WEB
  become: true
  roles:
    - sample