- name: Variable Types
  hosts: localhost
  connection: local
  vars:
    fruit_name: Orange # string
    quantity: 10 # number
    for_sale: true # boolean, Booleans supported by ansible are true/false, yes/no, Boolean comes string if you quote it.
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: Fruit Name - {{ fruit_name }}, Quantity - {{ quantity }}

