- name: Demo on Templates
  hosts: localhost
  connection: local
  vars:
    fruit_name: apple
  tasks:
    - name: Template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt